import numpy as np

class Testor:
    def __init__(self):
        self.test_inputs = ['this is one of the best movies i think it worth watching in cinema',
                            'i never saw a image as terrible as this regret to pay the my money',
                            'first time to see such a great movie and actors perform very professional',
                            'that boring film is no point to watch just do something else',
                            'this superb movie i will highly recommend and rate 5 out of 5',
                            'some of my favor films they plot as either mundane and hilarious',
                            'nice combination of the giant monster and samurai genres',
                            'no beer needed to enjoy this movie',
                            "with all the excessive violence in this film it could've been pg 13",
                            "this is a very realistic and romantic film with good plot",
                            "i felt like i was watching an example of how not to make a movie",
                            "this simply sensational movie should be oscar nominated",
                            "the story line is a joke and the tone doesn't fit the dialogue",
                            "hollywood ending terrifying atmosphere amazing book adaption",
                            "the characters didn't appeal to me and animation is looking cheap",
                            "design and locations and photography are strong assets of this film",
                            "i was particularly moved by the understated courage and integrity",
                            "different events happen in the movie you change your mind back and forth",
                            "not bad martial arts film fight scene are good",
                            "this film while not great it does effectively portray an intense moral dilemma"]

        self.test_labels = np.array([[1,0],
                                    [0,1],
                                    [1,0],
                                    [0,1],
                                    [1,0],
                                    [0,1],
                                    [1,0],
                                    [1,0],
                                    [0,1],
                                    [1,0],
                                    [0,1],
                                    [1,0],
                                    [0,1],
                                    [1,0],
                                    [0,1],
                                    [1,0],
                                    [1,0],
                                    [0,0],
                                    [0,0],
                                    [0,0]])
